### ISSUE TITLE
Behavior of isConnect has changed / been clarified and should be polled

### ISSUE THREAD

**Issue by rajsite** [labviewhacker/LVH-Leap#1]
In [Open.VI](https://github.com/labviewhacker/LVH-Leap/blob/ff92fbb278b668884839f10e54f06b6d016e4308/LabVIEW/vi.lib/LabVIEW%20Hacker/Leap/Public/Open.vi) the Controller.IsConnected method will frequently return false (using LEAP software 2.2.1) and the VI gives an error.

![capture7](https://cloud.githubusercontent.com/assets/1588923/5619453/bbb74238-94e7-11e4-834a-6d0e3df1e072.PNG)

The [Leap Motion docs](https://developer.leapmotion.com/documentation/cpp/api/Leap.Controller.html#cppclass_leap_1_1_controller_1a180fa55a4bf36580963bed9e3e09c227) indicate that isConnected should be polled

> When you first create a Controller object, isConnected() returns false. After the controller finishes initializing and connects to the Leap Motion software and if the Leap Motion hardware is plugged in, isConnected() returns true.
> 
> You can either handle the onConnect event using a Listener instance or poll the isConnected() function if you need to wait for your application to be connected to the Leap Motion software before performing some other operation.

**Comment by samkristoff** [comment]
I added a 3 second poll for isConnected() (seems to take on the order of a couple ms to connect).

This will be included in the 2.0 build.

-Sam K
